# Generated by Django 3.0.3 on 2020-02-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('tg_chat_id', models.BigIntegerField()),
                ('camera_url', models.CharField(max_length=2048)),
                ('time_range_start', models.TimeField()),
                ('time_range_finish', models.TimeField()),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
